apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    role: frontend
    env: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: aditya/image-frontend:v1
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://task.devops.in/api/tasks" #add your API_Load_Balancer DNS here
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
  type: ClusterIP
  selector:
   role: frontend
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
